'use client'
import { useEffect, useMemo, useState } from 'react'
import { createClient } from '@/lib/supabase/client'
type Voter={id:string;matric_number:string;surname:string;level:string;is_active:boolean;has_voted:boolean}
const levels=['100L','200L','300L','400L','500L']
export default function VotersPage(){const [rows,setRows]=useState<Voter[]>([]),[search,setSearch]=useState(''),[level,setLevel]=useState('ALL'),[voted,setVoted]=useState('ALL'),[eligible,setEligible]=useState('ALL'),[message,setMessage]=useState(''),[file,setFile]=useState<File|null>(null),[preview,setPreview]=useState<{valid:Voter[];invalid:number;duplicates:number}|null>(null)
async function load(){const {data,error}=await createClient().from('voters').select('id,matric_number,surname,level,is_active,has_voted').order('surname');if(error)setMessage(error.message);else setRows(data||[])}
useEffect(()=>{void load()},[]);const filtered=useMemo(()=>rows.filter(v=>(!search||`${v.matric_number} ${v.surname}`.toLowerCase().includes(search.toLowerCase()))&&(level==='ALL'||v.level===level)&&(voted==='ALL'||(voted==='VOTED'?v.has_voted:!v.has_voted))&&(eligible==='ALL'||(eligible==='ELIGIBLE'?v.is_active:!v.is_active))),[rows,search,level,voted,eligible]);const total=rows.length,eligibleCount=rows.filter(v=>v.is_active).length,votes=rows.filter(v=>v.has_voted).length
function parseCsv(text:string){const lines=text.split(/\r?\n/).filter(Boolean),head=lines.shift()?.split(',').map(x=>x.trim())||[],valid:Voter[]=[];let invalid=0,duplicates=0;const seen=new Set<string>();for(const line of lines){const cols=line.split(',').map(x=>x.trim()),record=Object.fromEntries(head.map((h,i)=>[h,cols[i]||'']));if(!record.matric_number||!record.surname||!levels.includes(record.level)||!['true','false'].includes(record.is_active?.toLowerCase())||seen.has(record.matric_number)){if(seen.has(record.matric_number))duplicates++;invalid++;continue}seen.add(record.matric_number);valid.push({id:'',matric_number:record.matric_number,surname:record.surname,level:record.level,is_active:record.is_active.toLowerCase()==='true',has_voted:false})}setPreview({valid,invalid,duplicates})}
async function importCsv(){if(!preview||!window.confirm(`Import ${preview.valid.length} valid voter records?`))return;const {error}=await createClient().from('voters').insert(preview.valid.map(({id,has_voted,...v})=>v));if(error)setMessage(error.message);else{setMessage(`Imported ${preview.valid.length} voters.`);setPreview(null);setFile(null);load()}}
return <section className="admin-content"><div className="page-heading"><div><p className="eyebrow">ELECTORAL COMMITTEE</p><h1>Voters</h1><p className="admin-copy">Review voter eligibility and participation. Individual ballot selections are never displayed.</p></div><label className="primary-button">Import CSV<input hidden type="file" accept=".csv,text/csv" onChange={async e=>{const f=e.target.files?.[0];if(f){setFile(f);parseCsv(await f.text())}}}/></label></div>{message&&<p className="admin-notice" role="status">{message}</p>}<div className="metric-grid"><div className="metric-card"><span>Total Registered Voters</span><strong>{total}</strong></div><div className="metric-card"><span>Eligible Voters</span><strong>{eligibleCount}</strong></div><div className="metric-card"><span>Votes Cast</span><strong>{votes}</strong></div><div className="metric-card"><span>Not Yet Voted</span><strong>{total-votes}</strong></div></div>{preview&&<div className="admin-panel"><div className="panel-heading"><h2>CSV validation preview</h2><span className="panel-count">{file?.name}</span></div><p className="admin-copy">Valid: {preview.valid.length} · Invalid: {preview.invalid} · Duplicate matric numbers: {preview.duplicates}</p><button className="primary-button" disabled={!preview.valid.length} onClick={importCsv}>Confirm import</button></div>}<section className="admin-panel"><div className="table-tools"><input placeholder="Search matric number or surname" value={search} onChange={e=>setSearch(e.target.value)}/><select value={level} onChange={e=>setLevel(e.target.value)}><option value="ALL">All levels</option>{levels.map(x=><option key={x}>{x}</option>)}</select><select value={voted} onChange={e=>setVoted(e.target.value)}><option value="ALL">All voting status</option><option value="VOTED">Voted</option><option value="NOT">Not Voted</option></select><select value={eligible} onChange={e=>setEligible(e.target.value)}><option value="ALL">All eligibility</option><option value="ELIGIBLE">Eligible</option><option value="NOT">Not Eligible</option></select><span>{filtered.length} records</span></div><div className="admin-table"><div className="table-head"><span>Matric Number</span><span>Surname</span><span>Level</span><span>Eligibility</span><span>Voting Status</span><span>Voted At</span></div>{filtered.map(v=><div className="table-row voter-row" key={v.id}><span>{v.matric_number}</span><span>{v.surname}</span><span>{v.level}</span><span>{v.is_active?'Eligible':'Not eligible'}</span><span>{v.has_voted?'Voted':'Not voted'}</span><span>—</span></div>)}</div></section></section>}
